.TH aqc "1" "8 December 2017" "User Commands"
.SH NAME
aqc \- Run aq command adding colour to output
.SH SYNOPSIS
.B aqc
.I command
.IR arguments ...
.br
.B aqs
.B -h
.RE
.SH DESCRIPTION
A substitute for the
.B aq
command which performs the same functionality except that the output will
be colourised by piping it through to
.BR ckey .
.SH "SEE ALSO"
.BR ckey (1),
.BR aqs (1).
.SH AUTHORS
Mark R. Bannister <mark.bannister@morganstanley.com>
.SH LICENSE
Use of this software is subject to the Apache 2 License:
.br
http://www.opensource.org/licenses/apache2.0

See source code for the COPYRIGHT file.
